---
- name: "Install Required Ubuntu Dependencies"
  apt:
    name:
      - apt-transport-https
      - dirmngr
      - fail2ban

- name: ensure ufw does not block anything
  community.general.ufw:
    state: enabled
    policy: allow

- name: make sure jail.d dir is empty (get rid of jail.d/defaults-debian.conf)

- name: add fail2ban jail definition

- name: restart and enable fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
    enabled: true
