---
# tasks file for pulmirror
- name: pulmirror | create mirror repos
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ solrmirror_root }}"

- name: pulmirror | add tls private key
  ansible.builtin.copy:
    src: "pulmirror_princeton_edu_priv.key"
    dest: "/etc/ssl/private/pulmirror_princeton_edu_priv.key"
    owner: root
    group: wheel
    mode: 0644

- name: pulmirror | add tls chained
  ansible.builtin.copy:
    src: "pulmirror_princeton_edu_chained.pem"
    dest: "/etc/ssl/pulmirror_princeton_edu_chained.pem"
    owner: root
    group: wheel
    mode: 0644

- name: pulmirror | Create httpd.conf
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: "{{ httpd_openbsd_conf_file }}"
    validate: httpd -n -f %s
  notify: restart obsd_httpd

- name: pulmirror | add daily cron
  ansible.builtin.copy:
    src: "files/daily.local.sh"
    dest: "/etc/daily.local"
    owner: root
    group: wheel
    mode: 0644
